name: rustup
version: 1.7.0
release: 1
source:
  - https://github.com/rust-lang-nursery/rustup.rs/archive/1.7.0.tar.gz : 8ee4602ca471594e879b9c74b65261355d055f815406854ba330129eab9a034f
license:
  - MIT
  - Apache-2.0
component: programming.tools
summary: The Rust toolchain installer
description: |
  rustup installs The Rust Programming Language from the official release channels,
  enabling you to easily switch between stable, beta, and nightly compilers and keep them updated.
  It makes cross-compiling simpler with binary builds of the standard library for common platforms.
builddeps:
  - cargo
networking: true
build: |
  cargo build --release --features no-self-update --bin rustup-init
install: |
  install -Dm755 $workdir/target/release/rustup-init $installdir/usr/bin/rustup
  ln -s /usr/bin/rustup $installdir/usr/bin/cargo
  ln -s /usr/bin/rustup $installdir/usr/bin/rustc
  ln -s /usr/bin/rustup $installdir/usr/bin/rustdoc
  ln -s /usr/bin/rustup $installdir/usr/bin/rust-gdb
  ln -s /usr/bin/rustup $installdir/usr/bin/rust-lldb
  ln -s /usr/bin/rustup $installdir/usr/bin/rls
